<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>best discount</name>
  <uuid>60c453e7-6bca-4552-a592-8321e06a78f8</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions
set 'the item discounted by line' to an Item in the items of 'the discount by product line' ; 
set 'the item discounted by group' to an Item in the items of 'the discount by product quantity'  
    where the name of 'the item discounted by line' is the name of this Item ; 
if the total line of 'the item discounted by line' is less than the total line of 'the item discounted by group' 
then 
add  a new Item where the unit price is
     the unit price of  'the item discounted by line', the discount per cent is  the discount per cent of 'the item discounted by line', the name is
     the name of 'the item discounted by line', the total line is 
     the total line of 'the item discounted by line', the quantity is
     the quantity of 'the item discounted by line' to the items of decision ;
else 
add  a new Item where the unit price is
     the unit price of  'the item discounted by group', the discount per cent is  the discount per cent of 'the item discounted by group', the name is
     the name of 'the item discounted by group', the total line is 
     the total line of 'the item discounted by group', the quantity is
     the quantity of 'the item discounted by group' to the items of decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
