<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>init</name>
  <uuid>27825de4-4636-4aff-b36a-2a741d0aa7fd</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[    set decision to a new Shopping Cart ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
