<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>salutation</name>
  <uuid>866c56fa-ee8f-44ec-bb2c-2f608e7046f4</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to "hello there!" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
