<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>business rule</name>
  <uuid>8a6dcea3-cf5b-4729-ade1-96cbaaad5519</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to <a date> ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
