<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>total price without discount</name>
  <uuid>3e426429-25b6-437a-95b7-89150b01a602</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 0 ;
for each Item in the items of 'the shopping cart' : 
- set decision to decision + the unit price of this Item * the quantity of this Item , ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
