<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>calculate discount percentage</name>
  <uuid>cc806b90-16d2-42f3-a5fc-43f6896fe770</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[for each Item called 'item' , in the items of decision 
   set the discount per cent of item to ( 100 - ( ( the total line of item / ( the unit price of item  * the quantity of item ) ) * 100 ) ) ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
