<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>init</name>
  <uuid>86eaf583-5df1-4da5-95b5-a0b8abe209a5</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 'the shopping cart' ; 
for each Item called 'item' , in the items of decision :
   - set the total line of item to the unit price of item * the quantity of item , ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
