<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>total with discount</name>
  <uuid>add0b284-603c-42c8-8bad-b636425dd344</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 0 ; 
for each Item in the items of 'the best discount' : 
    - set decision to decision + the total line of this Item , ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
