<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Print</name>
  <uuid>7410dd85-0f6e-4922-b4b4-f5496e25152a</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[print "Extra bags: " + decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
