<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>compute line total</name>
  <uuid>2983567d-3373-4d0b-ad9b-6a4f025ac3e7</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[for each Item called 'item' , in the items of decision 
   set the total line of item to ( ( the unit price of item * the quantity of item ) * ( ( 100 - the discount per cent of item ) / 100 ) ) ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
