<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>init</name>
  <uuid>7c937f7a-2aa9-4552-b7f9-1201ce181488</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 'the shopping cart' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
