<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output mapping rule</name>
  <uuid>be84703a-b412-43db-8ab3-fe04bea192fa</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if 'ML model invocation' is in error
 then 
set decision to a new risk probabilities where
        the no risk is 0.5, 
        the risk is 0.5 ;
else 
set decision to a new risk probabilities where
    the no risk is the probability no paymentdefault of 'ML model invocation' ,
    the risk is the probability paymentdefault of 'ML model invocation' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
