<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>f0544c6b-86bd-41a2-a488-639482d76296</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 'the state name';]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
