<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>total cart after discount</name>
  <uuid>b71a4995-61ab-4c02-ba27-ed2584babc7f</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to min( 'the discount on cart total' , 'the total after discount on products' ) ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
