<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Print fees</name>
  <uuid>3fc7b426-173b-4527-907c-8c5b880536c5</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[print "Extra bag: " + decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
