<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Zero bags</name>
  <uuid>767d2321-f8e0-41b6-8a69-fb33364922cc</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    'the extra bags' is 0
then
    set decision to 0 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
